### PR TITLE
Correct email address for Diversity mailing list and link to its archive

### PR DESCRIPTION
**Pull request by MartijnVisser**

### CODE REVIEW

**Review by pottekkat — COMMENTED** [review]
Could you also make a similar change in the "Practitioners" section? The mailing list and the link mentioned there are also wrong.

**Comment by aljam3h** [comment]
I got a document with authentication verification documents

I'm sorry for the late reply, I'm busy with education, my higher education.

**Review by atarora — APPROVED** [review]
Thank you ! LGTM!

**Review by jvz — APPROVED** [review]

**Comment by jvz** [comment]
Looks like we're all updated here now. Thanks for the PR!

**Pull request merged**
