### PR TITLE
[DI-11] Set up D&I website

### PR DESCRIPTION
**Pull request by jvz**
This is a simple Jekyll-based static site. I'm not sure how complicated this site will get, though Jekyll (like Pelican and other static site generators) is simple enough to build and deploy through ASF Jenkins.

Current preview of the Outreachy page:

Screen Shot 2019-07-28 at 12 49 37

### CODE REVIEW

**Comment by jvz** [comment]
Not really sure at the moment how to write a proper Dockerfile for this as combining both node and ruby seems somewhat annoying to do by hand.

**Comment by awasum** [comment]
@jvz , I will be able to pull this down, review and provide some feedback tomorrow night. My timezone is UTC + 1. if no one has done that by then. After that I Might be able to help dockerize the site.

There is a ruby-node docker image on dockerhub:  https://hub.docker.com/r/timbru31/ruby-node/

Maybe we use that as base builder...

But do we really need docker to get a simple website up and running? Maybe we are over engineering this thing.

**Comment by ShaneCurcuru** [comment]
Observation: my volunteer "hassle level" for easy contributions is checking out the source, reading the "How to build site" FAQ, making sure whatever Ruby gems the site needs are updated to version X, and running a command line (for me, on OSX).  If I have to install Docker, it's likely many contributors will fall out of the funnel before submitting patches. 
Thanks for the work to set it up!

**Comment by wohali** [comment]
Docker should only be necessary for the automated build, and can be visited later. Or it can be an alternative way of building things. There's nothing wrong with installing ruby+node and building it yourself on whatever OS you're on.

I'll try and help with the Dockerfile over the week, if people would like.

**Comment by jvz** [comment]
Exactly, @wohali. This project currently builds using rbenv since I thought that would make ruby easier to maintain in development, though the docker images I tried don't support `rbenv install` for some reason. The docker image was going to be for convenience, but mostly for use in building the site in CI.

**Comment by rubys** [comment]
I was able to build the site and test it using http://localhost:4000/ on an iMac using the following commands:

```
git clone git@github.com:jvz/diversity-site.git
cd diversity-site/
git checkout jekyll
bundle install
./rake.sh
```

I have ruby 2.3.7p456 and node v12.0.0 installed.

**Comment by jvz** [comment]
Running `bundle update` updates the dependencies in `Gemfile`. You should run `bundle install`. And the fact that `rake` worked by itself is good to know, but I added `rake` as a gem just in case (though I notice now that I have the same system ruby version as you).

**Comment by rubys** [comment]
I updated my comment.  I actually did a `bundle install` as I noted that you had checked in a lockfile.  Not sure why I posted `bundle update` instead.  I hadn't noticed that you had checked in a `rake.sh` file though.  I've now tried it and updated my comment.

**Comment by wohali** [comment]
@jvz +1

**Pull request closed without merging**
